# Site settings

title: "React and Jekyll"
email: "webmaster@redronin.com"
phone: "02 1234 5678"
phoneref: "0212345678"
address:
- GPO Box 000
- Canberra ACT 2601
description: >
  This is a template for a Jekyll site using Bootstrap theme with React
googleanalytics:

# Build settings

sass:
  style: compressed

exclude:
  - node_modules
  - package.json
  - gulpfile.js
  - firebase.js
  - README.md

# Gems

gems:
  - jekyll-babel

# Javascript files

javascript:
  - /js/jquery.js
  - /js/bootstrap.min.js
  - /js/react/react.js
  - /js/react/react-dom.js

# Define Menu Items for Main and Footer menu

menuitems:
  - url: /
    title: "Home"
  - url: /about/
    title: "About"
  - url: /search/
    title: "Search"
  - url: /contact/
    title: "Contact Us"
