# Site settings

title: "React and Jekyll"
email: "webmaster@redronin.com"
phone: "02 1234 5678"
phoneref: "0212345678"
address:
- GPO Box 000
- Canberra ACT 2601
description: >
  This is a template for a Jekyll site using Bootstrap theme with React
googleanalytics:

# Build settings

sass:
  style: compressed

# Javascript files

javascript:
  - /js/jquery.js
  - /js/bootstrap.min.js
  - /js/react/react.js
  - /js/react/react-dom.js

javascript-not-used:
  - https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.3/jquery.min.js
  - https://unpkg.com/bootstrap@3.3.6
  - /js/bootstrap.min.js
  - https://fb.me/react-15.0.2.js
  - https://fb.me/react-dom-15.0.2.js
  - https://unpkg.com/jquery@2.2.3
  - /js/jquery.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/react/15.0.2/react.min.js
  - https://unpkg.com/react@0.14.2/dist/react.js
  - https://unpkg.com/react-dom@0.14.2/dist/react-dom.js
  - /js/react/react.js
  - /js/react/react-dom.js
javascript-react-towel-has-these:
  - https://unpkg.com/react@0.14.2/dist/react.js
  - https://unpkg.com/react-dom@0.14.2/dist/react-dom.js
  - https://unpkg.com/throw-in-the-towel@2
babel-not-used-with-towel:
  - https://cdnjs.cloudflare.com/ajax/libs/babelcore/5.8.23/browser.min.js

# Define Menu Items for Main and Footer menu

menuitems:
  - url: /
    title: "Home"
  - url: /about/
    title: "About"
  - url: /search/
    title: "Search"
  - url: /contact/
    title: "Contact Us"
